
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://kaleko.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "David Kaleko"
title: "David Kaleko"
description: "Homepage of David Kaleko: Neutrino Physicist, Aspiring Data Scientist, and Chess Fanatic."
keywords: "david, kaleko, davidkaleko, blog, neutrino, physics, data science, data, science"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False

me-img: "/img/jetpacktocat.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"


########
# Blog #
########

post-preview-words: 15

paginate: 5

email-share: False
fb-share: False
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "kaleko"

syntax-highlight: True

###########
# Contact #
###########

email: "david (dot) kaleko (at) gmail (dot) com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/davidkaleko"
  - title: "github"
    url: "https://github.com/kaleko"
  - title: "lichess"
    url: "http://en.lichess.org/@/n3utrino"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
